version: "3.9"
services:
  app:
    build:
      # Assumes it will be copied in the build/ directory alongside the Dockerfiles.
      context: ./
      dockerfile: Dockerfile
    ports:
      # There is no proxy in Docker platform so expose the right ports!
      - "80:5000"
    # volumes:
    #   - "/tmp/db:/var/db"
    # environment:
    #   SQLITE_PATH: "/var/db/users.db"
