AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This is the AWS Serverless Application Model template
  that defines all the AWS resources we need for our Upstash Redis API.

Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  HelloGoRedisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/handler.zip
      Handler: handler
      Runtime: go1.x
      MemorySize: 512
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowCredentials: false
          AllowMethods: ["*"]
          AllowOrigins: ["*"]

Outputs:
  HelloGoRedisFunctionApi:
    Description: "Endpoint URL"
    Value: !GetAtt HelloGoRedisFunctionUrl.FunctionUrl
  HelloGoRedisFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt HelloGoRedisFunction.Arn
  HelloGoRedisFunctionIamRole:
    Description: "Implicit IAM Role created for HelloGoRedisFunction"
    Value: !GetAtt HelloGoRedisFunctionRole.Arn
